Add tool for embedding input fasta
songlab-cal/tape-neurips2019 pull request #5
Opened 2019-07-11 21:01 UTC by captaincapsaicin

Added the instructions on how to run in the README

This isn't super clean, because I couldn't figure out how to use the sacred `@command` api with the same config parameters.

2019-07-15 22:49 UTC, rmrao requested changes
So... the convert to tfrecords for embeddings and the `SequenceEmbedding` task seem like a weird way of doing this. I like having the fasta-to-tfrecord converter - that's helpful so that people can run the downstream tasks. But for just embedding fasta files, why don't we just use placeholders and run them through the model without all the rinokeras/tape specific code? Seems like a lot of code for that.

Specifically the embedding code could be something like:

```python
def embed_from_tfrecords(tfrecords_file, model: str, vocab=PFAM_VOCAB):
    sess = tf.Session()
    embedding_model = ModelBuilder.build_model(model)
    data = tf.data.TFRecordDataset(tfrecord_file).map(deserialize_protein_sequence)
    iterator = data.make_one_shot_iterator()
    batch = iterator.get_next()
    output = embedding_model(batch)
    embeddings = []
    with contextlib.suppress(tf.errors.OutOfRangeError):
        while True:
            encoder_output = sess.run(output['encoder_output'])
            embeddings.append(encoder_output)
    return embeddings
```
and
```python
def embed_from_fasta(fasta_file, model: str, vocab=PFAM_VOCAB):
    sess = tf.Session()
    embedding_model = ModelBuilder.build_model(model)
    sequence = tf.placeholder(tf.int32, [None, None])
    protein_length = tf.placeholder(tf.int32, [None])
    output = embedding_model({'sequence': sequence, 'protein_length': protein_length})
    embeddings = []
    for record in SeqIO.parse(filename, 'fasta'):
        int_sequence = np.array([vocab[aa] for aa in record.seq])
        encoder_output = sess.run(output['encoder_output'], feed_dict={sequence: int_sequence[None], protein_length: int_sequence.shape[1:]})
        embeddings.append(encoder_output)
    return embeddings
```

2019-07-15 22:49 UTC, rmrao commented on README.md
> +$ python tape/data_utils/serialize_fasta.py <filename>.fasta
Why not add this to the entrypoint also?

2019-07-15 22:49 UTC, rmrao commented on README.md
> +$ python tape/data_utils/serialize_fasta.py <filename>.fasta
`tape-serialize` or something

2019-07-17 21:40 UTC, captaincapsaicin commented on README.md
> +$ python tape/data_utils/serialize_fasta.py <filename>.fasta
That makes sense

2019-07-18 17:14 UTC, kodrzywolek commented on tape/run_embed.py
> +def embed_from_fasta(fasta_file, model: str, load_from=None, vocab=PFAM_VOCAB):
The code that was working for me:
```
def embed_from_fasta(fasta_file, model: str, load_from=None, vocab=PFAM_VOCAB):
    sess = tf.Session()
    embedding_model = ModelBuilder.build_model(model)

    primary = tf.placeholder(tf.int32, [None, None])
    protein_length = tf.placeholder(tf.int32, [None])
    output = embedding_model({'primary': primary, 'protein_length': protein_length})

    if load_from is not None:
        embedding_model.load_weights(load_from)

    sess.run(tf.global_variables_initializer())

    embeddings = []
    for record in SeqIO.parse(fasta_file, 'fasta'):
        int_sequence = np.array([vocab[aa] for aa in record.seq], ndmin=2)
        encoder_output = sess.run(output['encoder_output'], feed_dict={primary: int_sequence, protein_length: [len(record.seq)]})
        embeddings.append(encoder_output)
    return embeddings
```

2019-07-18 18:32 UTC, rmrao commented on tape/run_embed.py
> +def embed_from_fasta(fasta_file, model: str, load_from=None, vocab=PFAM_VOCAB):
This seems about right. I believe `sess.run(tf.global_variables_initializer())` should come before loading weights - otherwise the loaded weights are overridden.

2019-07-20 05:18 UTC, merged